name: Update Spring Boot Platform in embedded templates

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  update:
    name: Update Spring Boot Platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: knative/actions/setup-go@main
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Install NPM deps.
        run: npm install xml2js octokit@3.2.1 yaml semver
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: node ./hack/update-springboot-platform.js

